# -*- coding: utf-8 -*-
"""img_aug.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12b2iTm880g6NKaFxum4sdnkdWeJiHmDk
"""

from google.colab import drive
drive.flush_and_unmount()
drive.mount('/content/drive', force_remount=True)

import os
os.chdir('./drive/MyDrive/')

import os
import random
from scipy import ndarray
import numpy as np

# image processing library
import skimage as sk
from skimage import transform
from skimage import util
from skimage import io

from skimage.transform import AffineTransform, warp

def random_rotation(image_array: ndarray):
    # pick a random degree of rotation between 25% on the left and 25% on the right
    random_degree = random.uniform(-25, 25)
    return sk.transform.rotate(image_array, random_degree)

def random_noise(image_array: ndarray):
    # add random noise to the image
    return sk.util.random_noise(image_array)
    
def random_translate(image_array:ndarray):
    tform = transform.EuclideanTransform(rotation=np.pi/12.,translation=(100, -20))
    return transform.warp(image_array, tform.inverse)

# dictionary of the transformations we defined earlier
available_transformations = {
    'rotate': random_rotation,
    'noise': random_noise,
    'translate': random_translate
}

folder_path = '/content/drive/MyDrive/GradCAMClassDiaper/PP/'
num_files_desired = 300

# find all files paths from the folder
images = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

num_generated_files = 0
while num_generated_files <= num_files_desired:
    # random image from the folder
    image_path = random.choice(images)
    # read image as an two dimensional array of pixels
    image_to_transform = sk.io.imread(image_path)
    # random num of transformation to apply
    num_transformations_to_apply = random.randint(1, len(available_transformations))

    num_transformations = 0
    transformed_image = None
    while num_transformations <= num_transformations_to_apply:
        # random transformation to apply for a single image
        key = random.choice(list(available_transformations))
        transformed_image = available_transformations[key](image_to_transform)
        num_transformations += 1

    new_file_path = '%s/augmented_image_%s.jpg' % (folder_path, num_generated_files)

    # write image to the disk	
    io.imsave(new_file_path, transformed_image)
    num_generated_files += 1

